### ISSUE TITLE
Installer / Images / Setup

### ISSUE THREAD

**Issue by realsnick** [Sky360-Repository/sky360#1]
@RichardGHopf I'll suggest to start here a discussion around the sky360 installer and the vision to get to a sky360 image. Most likely this issue will split to more specific deliverables but for now we can discuss the basics for alpha.

**Comment by realsnick** [comment]
basic SD image for pi4 using nix is working and will be the foundation for the future . 

docker images are available for other linux based distribution (preffered specific board ubuntu based distro)

**Comment by Sky360Admin** [comment]
that is fantastic!
an image for the Pi5 is next I assume?

**Comment by realsnick** [comment]
They will take time as the board is new and no nix support yet. It's in the works though

**Comment by realsnick** [comment]
this work is complete by fabio for the time being
