### ISSUE TITLE
Idea - Video sample (From QHY183c Camera/Meike Lens) of Airplane (with timestamp & lat/long)

### ISSUE THREAD

**Issue by danlohman** [Sky360-Repository/sky360#17]
I'm looking for a video sample captured from the QHY183c and the Meike 3.5mm fisheye lens of an airplane flying though the field of view.  I'm looking for a video with the data below.  Thanks!

 - Time stamp 
 - Approximate Latitude 
 - Approximate Longitude

**Comment by realsnick** [comment]
duplicate of #16
