### ISSUE TITLE
QHY183 Camera Integration

### ISSUE THREAD

**Issue by realsnick** [Sky360-Repository/sky360#2]
This issue is to start document the thoughts behinds the integration of the QHY183 Camera.

The camera is capable of 20MP with 16bit per channel (RGGB). 

For now we are looking to choose a stable INDI Driver. Next steps are to measure its base performance. In parallel we will start consuming the INDI Video Stream on a ROS2 node and republish the video stream on ROS2.

**Comment by ibootstrapper** [comment]
short update. Christian did some work and recommend to start with the libindi-qhy 1.9.6

https://github.com/indilib/indi-3rdparty/archive/v1.9.6.tar.gz

There is a newer version 1.9.8 that will be tested as well

https://github.com/indilib/indi-3rdparty/archive/refs/tags/v1.9.8.tar.gz

**Comment by realsnick** [comment]
nixos is still in the works. PRs for libusb1 and fxload were accpeted to the merging branch

docker image is provided for amd64 and arm64... ubuntu server image is requirement for pi4, orange pi5 and NUC

**Comment by realsnick** [comment]
fxload is already a package on nix...working now on the qhy sdk package
