### ISSUE TITLE
Sky360 cannot be reached from a Major DNS provider (9.9.9.9)

### ISSUE THREAD

**Issue by katlol** [Sky360-Repository/sky360#21]
# Steps To Reproduce

- Browse https://dnschecker.org/#A/sky360.org
- Click Search

# Expected Result

Sky360 can be reached from all DNS

# Actual Result

<img width="628" alt="image" src="https://github.com/Sky360-Repository/sky360/assets/1695469/a1999fd4-6fbd-4d3d-810f-65bac14c0237">

# Proposed Mitigation

Move domain authorative DNS to an alternative provided unrelated to the registrar.

**Comment by realsnick** [comment]
@RichardGHopf the website is currently not accessible , verified on multiple countries.

**Comment by Sky360Admin** [comment]
we're using the website builder from UD, so the domain needs to be there as well as the nameservers. after switching back from cloudflare to UD, the website is reachable, but some subpages not. i have to check what's going on.

**Comment by realsnick** [comment]
@katlol do you have any recommendations around the website, hosting, etc? might be good to discuss it here

**Comment by katlol** [comment]
Not solved

<img width="688" alt="image" src="https://github.com/Sky360-Repository/sky360/assets/1695469/1b771516-3338-4e6e-866f-dbe1bf2a571d">


https://www.quad9.net/result/?url=sky360.org still blocked.

**Comment by katlol** [comment]
@realsnick @RichardGHopf your action required to solve this issue. Somebody representing Sky360 needs to contact Quad9 to unlock the domain.

**Comment by realsnick** [comment]
Closed by error

**Comment by realsnick** [comment]
@RichardGHopf do you want help on it?

**Comment by Sky360Admin** [comment]
issue solved
![image](https://github.com/Sky360-Repository/sky360/assets/92853151/76bb3e3e-f17d-48f8-9faa-ab17c21b7d01)
